[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/"
  to = "/public/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/public/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/discord/*"
  to = "https://discord.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/telegram/*"
  to = "https://api.telegram.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/openai/*"
  to = "https://api.openai.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/claude/*"
  to = "https://api.anthropic.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/gemini/*"
  to = "https://generativelanguage.googleapis.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/meta/*"
  to = "https://www.meta.ai/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/groq/*"
  to = "https://api.groq.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/xai/*"
  to = "https://api.x.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cohere/*"
  to = "https://api.cohere.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/huggingface/*"
  to = "https://router.huggingface.co/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/together/*"
  to = "https://api.together.xyz/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/novita/*"
  to = "https://api.novita.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/portkey/*"
  to = "https://api.portkey.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/fireworks/*"
  to = "https://api.fireworks.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/openrouter/*"
  to = "https://openrouter.ai/api/:splat"
  status = 200
  force = true
