name = "serverless-proxy"
main = "src/_worker.js"
compatibility_flags = ["nodejs_compat_v2"]  # 启用 Node.js 兼容模式
compatibility_date = "2025-05-20"
workers_dev = true

# -----------------------
# 统计分析配置
# -----------------------
[observability]
enabled = true
head_sampling_rate = 0.1
